// js/data.js - Core Game Data for Persona Labyrinth Roguelite (v5.2 - Content Expansion - FINAL ATTEMPT)

console.log("data.js loading... (v5.2 - Content Expansion - FINAL ATTEMPT)");

// --- Element Definitions (Trimmed for Roguelite Focus) ---
const elementDetails = {
    "Attraction": { name: "Attraction", coreQuestion: "Who or what sparks your initial desire?", coreConcept: "Your 'Desire Compass,' reacting to people, vibes, ideas, or aesthetics. It defines the 'who' or 'what' that initiates intrigue. Covers orientation, specific types, and demisexuality/asexuality.", examples: "Orientation (Straight, Gay, Bi, Pan, Ace, Demi), Sapiosexuality, Fetishes (Latex, Uniforms), Body Type preferences, Vibe/Energy.", },
    "Interaction": { name: "Interaction", coreQuestion: "How do you engage in the energetic dance of intimacy?", coreConcept: "The flow of energy and control between partners. Includes leading/following, giving/receiving, specific interaction styles (e.g., teasing, commanding), and communication within the dynamic.", examples: "Leading/Following, Top/Bottom/Versatile, Teasing, Commanding, Service, Communication Style, Primal Play.", },
    "Sensory": { name: "Sensory", coreQuestion: "What physical sensations resonate most strongly?", coreConcept: "Your 'Feeling Finder,' tuning into physical input. Covers quality of touch, temperature, texture, pressure, intensity, pain/pleasure spectrum, and influence of sight/sound/smell.", examples: "Gentle Touch, Firm Grip, Impact (Spanking/Flogging), Temperature (Wax/Ice), Textures (Latex/Silk/Rope), Bondage, Scents, Sounds.", },
    "Psychological": { name: "Psychological", coreQuestion: "What deeper 'why' fuels your intimate connections?", coreConcept: "The core motivations and emotional quests behind intimacy. Includes seeking connection, exploring power, self-expression, validation, stress relief, catharsis, or comfort/safety.", examples: "Seeking Connection, Power Exchange (Emotional Core), Validation Needs, Stress Relief, Catharsis, Vulnerability, Trust Building, Comfort/Security.", },
    "Cognitive": { name: "Cognitive", coreQuestion: "How much does your mind shape the experience?", coreConcept: "Your 'Mind Palace' engagement. Measures mental involvement: fantasy, scenarios, strategy, analysis, wordplay, or focus on abstract concepts versus pure presence.", examples: "Fantasy Immersion, Role-Playing, Dirty Talk, Banter, Strategy/Mind Games, Anticipation, Ritual/Protocol Focus, Presence/Mindfulness.", },
    "Relational": { name: "Relational", coreQuestion: "What relationship structure feels most authentic?", coreConcept: "Your preferred 'Constellation' for intimacy. Defines comfort with number of partners, commitment levels, and relationship styles (monogamy, polyamory, casual, etc.).", examples: "Monogamy, Polyamory, Open Relationships, Swinging, Casual Sex, Hookups, Solo Polyamory, Relationship Anarchy, Platonic Partnerships.", },
    "RoleFocus": { name: "RoleFocus", coreQuestion: "How important are defined D/s roles to your satisfaction?", coreConcept: "The 'Intensity Dial' for power dynamics. Measures the *salience* of Dominant/submissive/Switch roles versus other factors. High scores indicate roles are central; low scores suggest egalitarian preference.", examples: "Preference for D/s, Indifference to Roles, Egalitarian Focus, Needing Specific Role (Dom/Sub/Switch), Enjoying Power Exchange Intensity.", }
};

// --- Utility Maps & Arrays (Includes RoleFocus) ---
const elementKeyToFullName = { A: "Attraction", I: "Interaction", S: "Sensory", P: "Psychological", C: "Cognitive", R: "Relational", RF: "RoleFocus" };
const cardTypeKeys = ["Attack", "Skill", "Power", "Status", "Curse"];
const elementNames = ["Attraction", "Interaction", "Sensory", "Psychological", "Cognitive", "Relational", "RoleFocus"];

// --- Concepts Data (Mapped to Cards) ---
const concepts = [
    // --- STARTER CARDS ---
    { id: 10001, name: "Basic Strike", cardType: "Attack", visualHandle: "starter_strike.png", primaryElement: "I", elementScores: { A: 2, I: 5, S: 4, P: 1, C: 1, R: 1, RF: 2 }, briefDescription: "Deal 6 damage.", detailedDescription: "A simple, direct assertion.", rarity: 'starter', keywords: ['Attack', 'Simple'], lore: [ { level: 1, insightCost: 0, text: "The first step: Direct assertion.", unlocked: true } ] },
    { id: 10002, name: "Basic Defend", cardType: "Skill", visualHandle: "starter_defend.png", primaryElement: "P", elementScores: { A: 1, I: 2, S: 3, P: 5, C: 2, R: 2, RF: 1 }, briefDescription: "Gain 5 Block.", detailedDescription: "Bracing oneself.", rarity: 'starter', keywords: ['Block', 'Simple'], lore: [ { level: 1, insightCost: 0, text: "The shield raised: Basic protection.", unlocked: true } ] },
    { id: 10003, name: "Moment's Clarity", cardType: "Skill", visualHandle: "starter_clarity.png", primaryElement: "C", elementScores: { A: 1, I: 1, S: 1, P: 3, C: 5, R: 1, RF: 1 }, briefDescription: "Draw 1 card.", detailedDescription: "A brief flash of insight.", rarity: 'starter', keywords: ['Draw', 'Simple'], lore: [ { level: 1, insightCost: 0, text: "A fleeting thought, grasped.", unlocked: true } ] },

    // --- STATUS / CURSE CARDS ---
    { id: 20001, name: "Static", cardType: "Status", visualHandle: "status_static.png", primaryElement: null, elementScores: {}, briefDescription: "Unplayable.", detailedDescription: "Mental noise or interference.", rarity: 'special', keywords: ['Unplayable'], lore: [] },
    { id: 20002, name: "Dazed", cardType: "Status", visualHandle: "status_dazed.png", primaryElement: null, elementScores: {}, briefDescription: "Unplayable. Ethereal.", detailedDescription: "Temporary disorientation.", rarity: 'special', keywords: ['Unplayable', 'Ethereal'], lore: [] },
    { id: 20003, name: "Heavy Heart", cardType: "Curse", visualHandle: "curse_heavy_heart.png", primaryElement: null, elementScores: {}, briefDescription: "Unplayable.", detailedDescription: "Reduces Focus gained while in hand.", rarity: 'special', keywords: ['Unplayable', 'Curse'], lore: [] },
    { id: 20004, name: "Self-Doubt", cardType: "Curse", visualHandle: "curse_self_doubt.png", primaryElement: null, elementScores: {}, briefDescription: "Unplayable.", detailedDescription: "At the start of your turn, if in hand, lose 1 Strength.", rarity: 'special', keywords: ['Unplayable', 'Curse'], lore: [] },
    { id: 20005, name: "Wound", cardType: "Status", visualHandle: "status_wound.png", primaryElement: null, elementScores: {}, briefDescription: "Unplayable. Exhaust.", detailedDescription: "A lingering injury.", rarity: 'special', keywords: ['Unplayable', 'Exhaust'], lore: [] },

    // --- REGULAR CONCEPTS (Originals Revised + New Additions) ---
    { id: 1, name: "Vanilla Sex", cardType: "Attack", visualHandle: "common_vanilla.jpg", primaryElement: "S", elementScores: { A: 5, I: 5, S: 3, P: 4, C: 3, R: 4, RF: 1 }, briefDescription: "Deal 6 damage.", rarity: 'common', keywords: ['Attack', 'Simple', 'Familiar'], lore: [ { level: 1, insightCost: 3, text: "Foundation Stone.", unlocked: false }, { level: 2, insightCost: 7, text: "Comfort's Embrace.", unlocked: false }, { level: 3, insightCost: 12, text: "Hidden Depths.", unlocked: false} ] },
    { id: 2, name: "Sensual Touch", cardType: "Skill", visualHandle: "common_sensual_touch.jpg", primaryElement: "S", elementScores: { A: 4, I: 4, S: 4, P: 5, C: 2, R: 4, RF: 2 }, briefDescription: "Gain 5 Block. Heal 1.", rarity: 'common', keywords: ['Block', 'Heal', 'Gentle', 'Comfort'], lore: [ { level: 1, insightCost: 3, text: "Whispers on Skin.", unlocked: false }, { level: 2, insightCost: 7, text: "Mindful Moment.", unlocked: false }, { level: 3, insightCost: 12, text: "Foundation of Trust.", unlocked: false} ] },
    { id: 3, name: "Passionate Kissing", cardType: "Attack", visualHandle: "common_kissing.jpg", primaryElement: "S", elementScores: { A: 6, I: 5, S: 5, P: 6, C: 3, R: 5, RF: 3 }, briefDescription: "Deal 4 damage. Apply 1 Weak.", rarity: 'common', keywords: ['Attack', 'Debuff', 'Weak', 'Intensity'], lore: [ { level: 1, insightCost: 3, text: "The First Spark.", unlocked: false }, { level: 2, insightCost: 7, text: "Dialogue of Lips.", unlocked: false }, { level: 3, insightCost: 12, text: "Taste of Chemistry.", unlocked: false} ] },
    { id: 4, name: "Dominance (Psych)", cardType: "Power", visualHandle: "uncommon_dom_art.jpg", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 7, R: 6, RF: 9 }, briefDescription: "Start of turn: Apply 1 Vulnerable to a random enemy.", rarity: 'uncommon', keywords: ['Power', 'Control', 'Debuff', 'Vulnerable', 'Exhaust'], lore: [ { level: 1, insightCost: 3, text: "Fragment: Mind as instrument.", unlocked: false }, { level: 2, insightCost: 7, text: "Alchemist's Query.", unlocked: false }, { level: 3, insightCost: 15, text: "The Weight of Responsibility.", unlocked: false } ] },
    { id: 5, name: "Submission (Psych)", cardType: "Power", visualHandle: "uncommon_sub_art.jpg", primaryElement: "P", elementScores: { A: 6, I: 1, S: 5, P: 8, C: 5, R: 6, RF: 9 }, briefDescription: "Start of turn: If taking unblocked damage last turn, gain 3 Block.", rarity: 'uncommon', keywords: ['Power', 'Surrender', 'Block', 'Exhaust'], lore: [ { level: 1, insightCost: 3, text: "Reflection: Strength in yielding.", unlocked: false }, { level: 2, insightCost: 7, text: "Observation: Trust is currency.", unlocked: false }, { level: 3, insightCost: 15, text: "Active Choice, Not Weakness.", unlocked: false } ] },
    { id: 6, name: "Switching", cardType: "Power", visualHandle: "uncommon_switch.jpg", primaryElement: "I", elementScores: { A: 6, I: 5, S: 6, P: 7, C: 6, R: 6, RF: 8 }, briefDescription: "Start of turn: Gain 1 Strength and 1 Dexterity for this turn.", rarity: 'uncommon', keywords: ['Power', 'Fluidity', 'Buff', 'Strength', 'Dexterity', 'Temporary', 'Exhaust'], lore: [ { level: 1, insightCost: 3, text: "Maxim: 'Know both sides...'", unlocked: false }, { level: 2, insightCost: 7, text: "Dynamic Note: Shift is energy.", unlocked: false }, { level: 3, insightCost: 15, text: "Requires Communication.", unlocked: false } ] },
    { id: 7, name: "Impact Play (Light)", cardType: "Attack", visualHandle: "uncommon_impact_light.jpg", primaryElement: "S", elementScores: { A: 5, I: 6, S: 6, P: 5, C: 4, R: 5, RF: 6 }, briefDescription: "Deal 4 damage. Apply 1 Vulnerable.", rarity: 'uncommon', keywords: ['Attack', 'Impact', 'Debuff', 'Vulnerable', 'Playful'], lore: [ { level: 1, insightCost: 3, text: "Sensory Note: Light sting.", unlocked: false }, { level: 2, insightCost: 7, text: "Rhythm Focus.", unlocked: false }, { level: 3, insightCost: 15, text: "Gateway to Intensity.", unlocked: false } ] },
    { id: 8, name: "Impact Play (Heavy)", cardType: "Attack", visualHandle: "rare_impact_heavy.jpg", primaryElement: "S", elementScores: { A: 5, I: 7, S: 9, P: 7, C: 4, R: 6, RF: 8 }, briefDescription: "Deal 12 damage. Apply 1 Weak.", rarity: 'rare', keywords: ['Attack', 'Impact', 'Intensity', 'Pain', 'Debuff', 'Weak'], lore: [ { level: 1, insightCost: 8, text: "Alchemist's Journal: Resonance.", unlocked: false }, { level: 2, insightCost: 16, text: "Scrawled Note: Mark as proof.", unlocked: false }, { level: 3, insightCost: 25, text: "Requires Skill & Calibration.", unlocked: false } ] },
    { id: 9, name: "Sensation Play (Pain/Intensity Focus)", cardType: "Skill", visualHandle: "rare_pain.jpg", primaryElement: "S", elementScores: { A: 4, I: 6, S: 8, P: 7, C: 5, R: 6, RF: 8 }, briefDescription: "Apply 2 Vulnerable. Gain 1 Focus.", rarity: 'rare', keywords: ['Skill', 'Debuff', 'Vulnerable', 'Focus', 'Intensity', 'Pain'], lore: [ { level: 1, insightCost: 8, text: "Fragment: Meditation through fire.", unlocked: false }, { level: 2, insightCost: 16, text: "Herbalist's Wisdom.", unlocked: false }, { level: 3, insightCost: 25, text: "Psychological Landscape.", unlocked: false } ] },
    { id: 10, name: "Service Submission", cardType: "Skill", visualHandle: "uncommon_service.jpg", primaryElement: "I", elementScores: { A: 5, I: 2, S: 4, P: 7, C: 4, R: 6, RF: 8 }, briefDescription: "Gain 6 Block. Next turn, gain 1 Focus.", rarity: 'uncommon', keywords: ['Skill', 'Block', 'Focus', 'Service', 'Submission'], lore: [ { level: 1, insightCost: 3, text: "Devotional Echo.", unlocked: false }, { level: 2, insightCost: 7, text: "Observation: Purpose.", unlocked: false }, { level: 3, insightCost: 15, text: "Requires Clear Expectations.", unlocked: false } ] },
    { id: 11, name: "Command / Control Dynamics", cardType: "Power", visualHandle: "rare_control.jpg", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 8, R: 6, RF: 10 }, briefDescription: "Start of Turn: Gain 1 Focus. Attacks deal +2 damage this turn.", rarity: 'rare', keywords: ['Power', 'Control', 'Command', 'Focus', 'Buff', 'Exhaust'], lore: [ { level: 1, insightCost: 9, text: "Tattered Scroll: Voice commands.", unlocked: false }, { level: 2, insightCost: 18, text: "Alchemist's Query: Thrill?", unlocked: false }, { level: 3, insightCost: 28, text: "Foundation of Trust.", unlocked: false } ] },
    { id: 12, name: "Objectification Play", cardType: "Skill", visualHandle: "rare_object.jpg", primaryElement: "P", elementScores: { A: 7, I: 4, S: 6, P: 8, C: 6, R: 5, RF: 8 }, briefDescription: "Target loses 2 Strength. Gain 8 Block.", rarity: 'rare', keywords: ['Skill', 'Debuff', 'Strength', 'Block', 'Objectification', 'Control'], lore: [ { level: 1, insightCost: 8, text: "Philosophical Fragment.", unlocked: false }, { level: 2, insightCost: 16, text: "Warning Label: Consent.", unlocked: false }, { level: 3, insightCost: 25, text: "Can Be Both Ways.", unlocked: false } ] },
    { id: 13, name: "Role-Playing (Scenario)", cardType: "Skill", visualHandle: "uncommon_roleplay.jpg", primaryElement: "C", elementScores: { A: 6, I: 6, S: 5, P: 6, C: 8, R: 6, RF: 5 }, briefDescription: "Gain 1 Focus. Draw 2 cards.", rarity: 'uncommon', keywords: ['Skill', 'Focus', 'Draw', 'RolePlay', 'Cognitive'], lore: [ { level: 1, insightCost: 3, text: "Actor's Insight.", unlocked: false }, { level: 2, insightCost: 7, text: "Narrative Power.", unlocked: false }, { level: 3, insightCost: 15, text: "Improvisation vs. Script.", unlocked: false } ] },
    { id: 14, name: "Fantasy Immersion", cardType: "Power", visualHandle: "rare_fantasy.jpg", primaryElement: "C", elementScores: { A: 5, I: 3, S: 4, P: 7, C: 9, R: 3, RF: 3 }, briefDescription: "At the start of your turn, gain 5 Block if your hand is full.", rarity: 'rare', keywords: ['Power', 'Fantasy', 'Cognitive', 'Block', 'Conditional', 'Exhaust'], lore: [ { level: 1, insightCost: 9, text: "Dream Journal: Story mattered.", unlocked: false }, { level: 2, insightCost: 18, text: "Mapmaker's Note: Details.", unlocked: false }, { level: 3, insightCost: 28, text: "Can Be Shared or Solo.", unlocked: false } ] },
    { id: 15, name: "Deep Emotional Intimacy", cardType: "Power", visualHandle: "uncommon_intimacy_art.jpg", primaryElement: "P", elementScores: { A: 7, I: 5, S: 4, P: 9, C: 5, R: 7, RF: 2 }, briefDescription: "At the end of your turn, gain 2 Regen.", rarity: 'uncommon', keywords: ['Power', 'Heal', 'Regen', 'Connection', 'Exhaust'], lore: [ { level: 1, insightCost: 3, text: "Vulnerability as Strength.", unlocked: false }, { level: 2, insightCost: 7, text: "Soul Gazing.", unlocked: false }, { level: 3, insightCost: 15, text: "Foundation for Exploration.", unlocked: false } ] },
    { id: 16, name: "Rope Bondage (Shibari/Kinbaku)", cardType: "Skill", visualHandle: "rare_rope.jpg", primaryElement: "S", elementScores: { A: 6, I: 7, S: 8, P: 7, C: 6, R: 6, RF: 8 }, briefDescription: "Apply 2 Weak and 2 Frail to target enemy.", rarity: 'rare', keywords: ['Skill', 'Debuff', 'Weak', 'Frail', 'Control', 'Restriction'], lore: [ { level: 1, insightCost: 8, text: "Rigger's Maxim: Trust knot.", unlocked: false }, { level: 2, insightCost: 16, text: "Historical Note: Hojojutsu.", unlocked: false }, { level: 3, insightCost: 25, text: "Energetic Exchange.", unlocked: false } ] },
    { id: 17, name: "Restriction / Helplessness", cardType: "Skill", visualHandle: "rare_restrict.jpg", primaryElement: "P", elementScores: { A: 5, I: 3, S: 7, P: 9, C: 5, R: 5, RF: 8 }, briefDescription: "Gain 12 Block. Cannot be targeted by enemies next turn.", rarity: 'rare', keywords: ['Skill', 'Block', 'Evasion', 'Helplessness', 'Surrender', 'Exhaust'], lore: [ { level: 1, insightCost: 8, text: "Inner Monologue: Just be.", unlocked: false }, { level: 2, insightCost: 16, text: "Philosopher's Query: Appeal?", unlocked: false }, { level: 3, insightCost: 25, text: "Requires Deep Trust.", unlocked: false } ] },
    { id: 18, name: "Exhibitionism", cardType: "Skill", visualHandle: "uncommon_exhibit.jpg", primaryElement: "I", elementScores: { A: 6, I: 7, S: 5, P: 7, C: 6, R: 5, RF: 5 }, briefDescription: "Deal 3 damage to ALL enemies. Gain 1 Strength.", rarity: 'uncommon', keywords: ['Attack', 'AOE', 'Buff', 'Strength', 'Performance', 'Exhibitionist'], lore: [ { level: 1, insightCost: 3, text: "Performer's Thrill.", unlocked: false }, { level: 2, insightCost: 7, text: "Mirror Effect.", unlocked: false }, { level: 3, insightCost: 15, text: "Consent is Key.", unlocked: false } ] },
    { id: 19, name: "Voyeurism", cardType: "Skill", visualHandle: "uncommon_voyeur.jpg", primaryElement: "A", elementScores: { A: 7, I: 2, S: 3, P: 6, C: 5, R: 3, RF: 2 }, briefDescription: "Gain 5 Block. Draw 1 card.", rarity: 'uncommon', keywords: ['Skill', 'Block', 'Draw', 'Observation', 'Voyeur'], lore: [ { level: 1, insightCost: 3, text: "Observer's Paradox.", unlocked: false }, { level: 2, insightCost: 7, text: "Power in Looking.", unlocked: false }, { level: 3, insightCost: 15, text: "Consent Matters Here Too.", unlocked: false } ] },
    { id: 20, name: "Latex / Material Fetish", cardType: "Skill", visualHandle: "rare_latex.jpg", primaryElement: "A", elementScores: { A: 9, I: 5, S: 8, P: 6, C: 5, R: 4, RF: 5 }, briefDescription: "Gain 8 Block and 1 Dexterity.", rarity: 'rare', keywords: ['Skill', 'Block', 'Buff', 'Dexterity', 'Fetish', 'Material', 'Latex', 'Exhaust'], lore: [ { level: 1, insightCost: 9, text: "Texture Note: Second skin.", unlocked: false }, { level: 2, insightCost: 18, text: "Alchemist's Insight: Catalyst.", unlocked: false }, { level: 3, insightCost: 28, text: "Sensory Immersion.", unlocked: false } ] },
    { id: 21, name: "Uniform / Clothing Fetish", cardType: "Power", visualHandle: "rare_uniform.jpg", primaryElement: "A", elementScores: { A: 8, I: 6, S: 4, P: 6, C: 6, R: 5, RF: 5 }, briefDescription: "Interaction cards cost 1 less Focus (min 0).", rarity: 'rare', keywords: ['Power', 'Fetish', 'Clothing', 'Uniform', 'CostReduction', 'Exhaust'], lore: [ { level: 1, insightCost: 8, text: "Costumer's Thread.", unlocked: false }, { level: 2, insightCost: 16, text: "Psychological Note: Signifier.", unlocked: false }, { level: 3, insightCost: 25, text: "Beyond the Look.", unlocked: false } ] },

    // --- NEW CONCEPTS ---
    { id: 100, name: "Quick Jab", cardType: "Attack", visualHandle: "attack_jab.png", primaryElement: "I", elementScores: { I: 6, S: 4, P: 2, RF: 3 }, briefDescription: "Deal 4 damage. Draw 1 card if this defeats an enemy.", rarity: 'common', keywords: ['Attack', 'ConditionalDraw'], lore: [] },
    { id: 101, name: "Teasing Strike", cardType: "Attack", visualHandle: "attack_tease.png", primaryElement: "I", elementScores: { I: 5, P: 4, C: 4, A: 5 }, briefDescription: "Deal 3 damage. Apply 1 Vulnerable.", rarity: 'common', keywords: ['Attack', 'Debuff', 'Vulnerable', 'Playful'], lore: [] },
    { id: 102, name: "Focused Blow", cardType: "Attack", visualHandle: "attack_focus.png", primaryElement: "C", elementScores: { C: 7, I: 4, S: 3 }, briefDescription: "Deal 8 damage. Scry 1.", rarity: 'common', keywords: ['Attack', 'Scry', 'Cognitive'], lore: [] },
    { id: 103, name: "Sensory Tap", cardType: "Attack", visualHandle: "attack_sensory.png", primaryElement: "S", elementScores: { S: 7, P: 3, I: 4 }, briefDescription: "Deal 5 damage. Gain 1 Focus.", rarity: 'common', keywords: ['Attack', 'Focus', 'Sensory'], lore: [] },
    { id: 67, name: "Oral Sex", cardType: "Attack", visualHandle: "attack_oral.png", primaryElement: "S", elementScores: { A: 6, I: 5, S: 7, P: 5, C: 3, R: 5, RF: 4 }, briefDescription: "Deal 7 damage. Apply 1 Vulnerable.", rarity: 'common', keywords: ['Attack', 'Debuff', 'Vulnerable', 'Sensory'], lore: [/* ... */]},
    { id: 104, name: "Observe", cardType: "Skill", visualHandle: "skill_observe.png", primaryElement: "C", elementScores: { C: 6, P: 4, I: 2 }, briefDescription: "Gain 4 Block. Scry 2.", rarity: 'common', keywords: ['Skill', 'Block', 'Scry'], lore: [] },
    { id: 105, name: "Quick Guard", cardType: "Skill", visualHandle: "skill_guard.png", primaryElement: "P", elementScores: { P: 6, S: 4, I: 3 }, briefDescription: "Gain 7 Block.", rarity: 'common', keywords: ['Skill', 'Block'], lore: [] },
    { id: 106, name: "Prepare", cardType: "Skill", visualHandle: "skill_prepare.png", primaryElement: "C", elementScores: { C: 5, P: 4, I: 3 }, briefDescription: "Gain 3 Block. Draw 1 card.", rarity: 'common', keywords: ['Skill', 'Block', 'Draw'], lore: [] },
    { id: 107, name: "Minor Adjustment", cardType: "Skill", visualHandle: "skill_adjust.png", primaryElement: "I", elementScores: { I: 4, C: 4, P: 3 }, briefDescription: "Gain 2 Block. Gain 1 Focus.", rarity: 'common', keywords: ['Skill', 'Block', 'Focus'], lore: [] },
    { id: 31, name: "Cuddling / Affection", cardType: "Skill", visualHandle: "skill_cuddle.png", primaryElement: "P", elementScores: { A: 4, I: 3, S: 5, P: 7, C: 3, R: 6, RF: 1 }, briefDescription: "Gain 4 Block. Heal 2.", rarity: 'common', keywords: ['Skill', 'Block', 'Heal', 'Comfort'], lore: [/*...*/] },
    { id: 32, name: "Dirty Talk", cardType: "Skill", visualHandle: "skill_dirtytalk.png", primaryElement: "C", elementScores: { A: 5, I: 6, S: 2, P: 4, C: 7, R: 4, RF: 5 }, briefDescription: "Apply 1 Vulnerable. Draw 1 card.", rarity: 'common', keywords: ['Skill', 'Debuff', 'Vulnerable', 'Draw', 'Cognitive'], lore: [/* ... */]},
    { id: 74, name: "Flirting / Banter", cardType: "Skill", visualHandle: "skill_banter.png", primaryElement: "I", elementScores: { A: 6, I: 7, S: 3, P: 5, C: 6, R: 5, RF: 4 }, briefDescription: "Apply 1 Weak. Draw 1 card.", rarity: 'common', keywords: ['Skill', 'Debuff', 'Weak', 'Draw', 'Interaction'], lore: [/* ... */]},
    { id: 108, name: "Calculated Strike", cardType: "Attack", visualHandle: "attack_calc.png", primaryElement: "C", elementScores: { C: 8, I: 5, S: 4 }, briefDescription: "Deal damage equal to 2x Focus.", rarity: 'uncommon', keywords: ['Attack', 'Scaling', 'Cognitive'], lore: [] },
    { id: 109, name: "Psychological Blow", cardType: "Attack", visualHandle: "attack_psych.png", primaryElement: "P", elementScores: { P: 8, I: 6, C: 4 }, briefDescription: "Deal 8 damage. If the target intends to Attack, gain 4 Block.", rarity: 'uncommon', keywords: ['Attack', 'ConditionalBlock', 'Psychological'], lore: [] },
    { id: 110, name: "Relational Strike", cardType: "Attack", visualHandle: "attack_rel.png", primaryElement: "R", elementScores: { R: 8, I: 5, P: 5 }, briefDescription: "Deal 6 damage. Apply 2 Weak.", rarity: 'uncommon', keywords: ['Attack', 'Debuff', 'Weak', 'Relational'], lore: [] },
    { id: 40, name: "Primal Play", cardType: "Attack", visualHandle: "attack_primal.png", primaryElement: "S", elementScores: { A: 5, I: 7, S: 8, P: 6, C: 2, R: 4, RF: 6 }, briefDescription: "Deal 5 damage. Apply 1 Weak.", rarity: 'uncommon', keywords: ['Attack', 'Debuff', 'Weak', 'Primal'], lore: [/* ... */]},
    { id: 111, name: "Heightened Senses", cardType: "Skill", visualHandle: "skill_senses.png", primaryElement: "S", elementScores: { S: 8, C: 4, P: 5 }, briefDescription: "Gain 2 Dexterity. Draw 1 card.", rarity: 'uncommon', keywords: ['Skill', 'Buff', 'Dexterity', 'Draw', 'BuffSelf'], lore: [] },
    { id: 112, name: "Redirect Aggression", cardType: "Skill", visualHandle: "skill_redirect.png", primaryElement: "I", elementScores: { I: 8, P: 5, C: 4 }, briefDescription: "Gain Block equal to the highest incoming damage.", rarity: 'uncommon', keywords: ['Skill', 'Block', 'Reactive', 'Interaction'], lore: [] },
    { id: 113, name: "Inner Peace", cardType: "Skill", visualHandle: "skill_peace.png", primaryElement: "P", elementScores: { P: 9, S: 3, C: 4 }, briefDescription: "Gain 10 Block. Heal 3.", rarity: 'uncommon', keywords: ['Skill', 'Block', 'Heal', 'Comfort'], lore: [] },
    { id: 46, name: "Compliments / Praise", cardType: "Skill", visualHandle: "skill_praise.png", primaryElement: "P", elementScores: { A: 4, I: 5, S: 2, P: 7, C: 4, R: 6, RF: 5 }, briefDescription: "Gain 3 Block. Apply 1 Strength to yourself.", rarity: 'uncommon', keywords: ['Skill', 'Block', 'Buff', 'Strength', 'BuffSelf'], lore: [/* ... */]},
    { id: 49, name: "Shared Fantasy Talk", cardType: "Skill", visualHandle: "skill_fantasy_talk.png", primaryElement: "C", elementScores: { A: 5, I: 5, S: 2, P: 6, C: 8, R: 6, RF: 3 }, briefDescription: "Draw 2 cards. Gain 1 Focus.", rarity: 'uncommon', keywords: ['Skill', 'Draw', 'Focus', 'Cognitive', 'Fantasy'], lore: [/* ... */]},
    { id: 114, name: "Cognitive Flow", cardType: "Power", visualHandle: "power_cogflow.png", primaryElement: "C", elementScores: { C: 9, P: 4, I: 3 }, briefDescription: "Whenever you draw 3+ cards in a turn, gain 1 Focus.", rarity: 'uncommon', keywords: ['Power', 'Focus', 'Draw'], lore: [] },
    { id: 115, name: "Sensory Shield", cardType: "Power", visualHandle: "power_senshield.png", primaryElement: "S", elementScores: { S: 8, P: 5, I: 3 }, briefDescription: "Whenever you play 3 Skills in a turn, gain 6 Block.", rarity: 'uncommon', keywords: ['Power', 'Block', 'Skill'], lore: [] },
    { id: 116, name: "All-Out Assault", cardType: "Attack", visualHandle: "attack_allout.png", primaryElement: "I", elementScores: { I: 9, S: 7, P: 3, RF: 7 }, briefDescription: "Deal 7 damage to ALL enemies.", rarity: 'rare', keywords: ['Attack', 'AOE', 'Interaction'], lore: [] },
    { id: 117, name: "Finishing Touch", cardType: "Attack", visualHandle: "attack_finish.png", primaryElement: "S", elementScores: { S: 9, I: 5, A: 6 }, briefDescription: "Deal 10 damage. If this defeats an enemy, gain 2 Focus.", rarity: 'rare', keywords: ['Attack', 'ConditionalFocus', 'Sensory'], lore: [] },
    { id: 118, name: "Mind Shatter", cardType: "Attack", visualHandle: "attack_mindshatter.png", primaryElement: "C", elementScores: { C: 9, P: 6, I: 3 }, briefDescription: "Deal 5 damage. Discard your hand. Draw that many cards.", rarity: 'rare', keywords: ['Attack', 'Discard', 'Draw', 'Cognitive', 'Risky'], lore: [] },
    { id: 119, name: "Deep Analysis", cardType: "Skill", visualHandle: "skill_analysis.png", primaryElement: "C", elementScores: { C: 9, P: 6, I: 3 }, briefDescription: "Draw 3 cards. Discard 1 card.", rarity: 'rare', keywords: ['Skill', 'Draw', 'Discard', 'Cognitive'], lore: [] },
    { id: 120, name: "Share Burden", cardType: "Skill", visualHandle: "skill_share.png", primaryElement: "R", elementScores: { R: 9, P: 7, I: 4 }, briefDescription: "Gain 8 Block. Transfer all your Debuffs to target enemy.", rarity: 'rare', keywords: ['Skill', 'Block', 'Debuff', 'Transfer', 'Relational'], lore: [] },
    { id: 135, name: "Embrace Pain", cardType: "Skill", visualHandle: "painslut.jpg", primaryElement: "S", elementScores: { A: 4, I: 2, S: 9, P: 8, C: 4, R: 5, RF: 8 }, briefDescription: "Take 3 damage. Gain 2 Strength. Draw 1 card.", rarity: 'rare', keywords: ['Skill', 'Pain', 'Buff', 'Strength', 'Draw', 'SelfDamage'], lore: [/* ... */]},
    { id: 51, name: "Stress Relief Focus", cardType: "Skill", visualHandle: "skill_stressrelief.png", primaryElement: "P", elementScores: { A: 3, I: 3, S: 5, P: 9, C: 6, R: 4, RF: 2 }, briefDescription: "Gain 9 Block. Heal 2. Exhaust.", rarity: 'rare', keywords: ['Skill', 'Block', 'Heal', 'Comfort', 'Exhaust'], lore: [/* ... */]},
    { id: 121, name: "Flow State", cardType: "Power", visualHandle: "power_flow.png", primaryElement: "C", elementScores: { C: 9, S: 5, P: 6 }, briefDescription: "Whenever you play 3 cards of the same type in a turn, draw 1 card.", rarity: 'rare', keywords: ['Power', 'Draw', 'Combo'], lore: [] },
    { id: 122, name: "Resilience", cardType: "Power", visualHandle: "power_resilience.png", primaryElement: "P", elementScores: { P: 9, S: 5, R: 6 }, briefDescription: "At the start of your turn, gain Block equal to the number of Curses in your hand.", rarity: 'rare', keywords: ['Power', 'Block', 'Curse', 'Defensive'], lore: [] },
    { id: 123, name: "Deep Connection", cardType: "Power", visualHandle: "power_connection.png", primaryElement: "R", elementScores: { R: 9, P: 7, I: 5 }, briefDescription: "At the start of combat, Shuffle 2 'Supportive Word' into your draw pile.", rarity: 'rare', keywords: ['Power', 'Support', 'Relational'], lore: [] },
    { id: 124, name: "Supportive Word", cardType: "Skill", visualHandle: "skill_support.png", primaryElement: "R", elementScores: { R: 7, P: 5 }, briefDescription: "Gain 3 Block. Draw 1 card. Exhaust.", rarity: 'special', keywords: ['Skill', 'Block', 'Draw', 'Exhaust', 'Fleeting'], lore: [] },
     // Placeholder for concept 25 if needed for quiz map
     { id: 25, name: "Ethical Polyamory", cardType: "Power", visualHandle: "power_poly.png", primaryElement: "R", elementScores: { R: 9, C: 7, P: 6, I: 5 }, briefDescription: "Gain 1 Focus. Draw 1 card.", rarity: 'rare', keywords: ['Power', 'Relational', 'Communication', 'Exhaust'], lore: [] }, // Example definition


]; // END OF CONCEPTS ARRAY


// --- Milestones ---
const milestones = [ /* ... FULL MILESTONE LIST ... */
    { id: "msR001", description: "First Step Taken", reward: { type: "insight", amount: 10 }, track: { action: "startRun", count: 1 } },
    { id: "msR002", description: "Combat Initiate", reward: { type: "insight", amount: 15 }, track: { action: "winCombat", count: 1 } },
    { id: "msR003", description: "Elite Challenger", reward: { type: "unlockArtifact", artifactId: 'resonant_echo_s' }, track: { action: "winElite", count: 1 } },
    { id: "msR004", description: "Floor 1 Cleared", reward: { type: "increaseMaxIntegrity", amount: 5 }, track: { action: "victory_floor_1", count: 1 } },
    { id: "msR005", description: "Deep Insight", reward: { type: "insight", amount: 30 }, track: { action: "reachFloor", value: 2 } },
    { id: "msR006", description: "Floor 2 Cleared", reward: { type: "increaseStartingFocus", amount: 1 }, track: { action: "victory_floor_2", count: 1 } },
    { id: "msR007", description: "Heart of the Labyrinth", reward: { type: "insight", amount: 50 }, track: { action: "reachFloor", value: 3 } },
    { id: "msR008", description: "Labyrinth Conquered!", reward: { type: "unlockArtifact", artifactId: 'alchemists_stone_x' }, track: { action: "runVictory", count: 1 } },
    { id: "msR009", description: "Persistent Explorer", reward: { type: "increaseStartingInsight", amount: 10 }, track: { action: "runCompleted", count: 5 } },
    { id: "msR010", description: "Seasoned Veteran", reward: { type: "unlockCard", cardId: 101 }, track: { action: "runCompleted", count: 15 } },
    { id: "msC001", description: "Flawless Victory", reward: { type: "insight", amount: 20 }, track: { action: "winCombatFlawless", count: 1 } },
    { id: "msC002", description: "Overkill", reward: { type: "insight", amount: 15 }, track: { action: "dealHighDamageAttack", value: 50 } },
    { id: "msC003", description: "Impenetrable", reward: { type: "insight", amount: 10 }, track: { action: "endTurnHighBlock", value: 30 } },
    { id: "msC004", description: "Combo Master", reward: { type: "unlockCard", cardId: 74 }, track: { action: "playManyCardsTurn", value: 8 } },
    { id: "msC005", description: "Debilitator", reward: { type: "insight", amount: 25 }, track: { action: "defeatEnemyWithDebuffs", value: 3 } },
    { id: "msRes01", description: "Focused Mind", reward: { type: "unlockArtifact", artifactId: 'focus_lens_c' }, track: { state: "playerMaxFocus", threshold: 10 } },
    { id: "msRes02", description: "Resilient Form", reward: { type: "unlockCard", cardId: 15 }, track: { state: "playerMaxIntegrity", threshold: 100 } },
    { id: "msRes03", description: "Insight Hoarder", reward: { type: "insight", amount: 25 }, track: { action: "holdHighInsight", value: 200 } },
    { id: "msN001", description: "Wise Choice", reward: { type: "insight", amount: 20 }, track: { action: "resolveDilemma", count: 5 } },
    { id: "msN002", description: "Eventful Journey", reward: { type: "unlockCard", cardId: 13 }, track: { action: "completeReflection", count: 10 } },
    { id: "msN003", description: "Savvy Shopper", reward: { type: "increaseShopArtifactChoices", amount: 1 }, track: { action: "buyAnyShopItem", count: 5 } },
    { id: "msN004", description: "Well Rested", reward: { type: "increaseStartingInsight", amount: 5 }, track: { action: "useAnyRestAction", count: 10 } },
    { id: "msN005", description: "Deck Refiner", reward: { type: "unlockArtifact", artifactId: 'cartographers_pen_r' }, track: { action: "removeCard", count: 5 } },
    { id: "msCol01", description: "Collector", reward: { type: "increaseCardRewardChoices", amount: 1 }, track: { state: "unlockedConcepts.size", threshold: 25 } },
    { id: "msCol02", description: "Archivist", reward: { type: "insight", amount: 50 }, track: { state: "unlockedConcepts.size", threshold: 50 } },
    { id: "msCol03", description: "Relic Hunter", reward: { type: "insight", amount: 30 }, track: { state: "unlockedArtifacts.size", threshold: 10 } },
    { id: "msCol04", description: "Master Librarian", reward: { type: "insight", amount: 75 }, track: { state: "unlockedConcepts.size", threshold: 75 } },
    { id: "msCol05", description: "Artifact Master", reward: { type: "unlockArtifact", artifactId: 'philosophers_catalyst_p' }, track: { state: "unlockedArtifacts.size", threshold: 20 } },
    { id: "msA001", description: "First Ascent", reward: { type: "insight", amount: 50 }, track: { action: "winAscension", value: 1 } },
    { id: "msA005", description: "Steadfast Climb", reward: { type: "increaseMaxIntegrity", amount: 10 }, track: { action: "winAscension", value: 5 } },
    { id: "msA010", description: "Peak Performer", reward: { type: "unlockArtifact", artifactId: 'labyrinth_map_r' }, track: { action: "winAscension", value: 10 } },
];

// --- Elemental Dilemmas ---
 const elementalDilemmas = [ /* ... FULL DILEMMA LIST ... */
    { id: "ED_A01", elementFocus: ["A", "P"], situation: "Intense physical attraction [A] vs. need for deeper connection [P].", question: "Where does your energy flow?", sliderMinLabel: "Psychological Depth (P)", sliderMaxLabel: "Intense Attraction (A)", elementKeyMin: "P", elementKeyMax: "A" },
    { id: "ED_A02", elementFocus: ["A", "R"], situation: "New attraction [A] potentially causes friction with existing relationships [R].", question: "Primary leaning?", sliderMinLabel: "Relationship Stability (R)", sliderMaxLabel: "New Attraction (A)", elementKeyMin: "R", elementKeyMax: "A" },
    { id: "ED_I03", elementFocus: ["I", "RF"], situation: "Preference for fluid interaction [I] vs. partner's desire for fixed roles [RF].", question: "Your response?", sliderMinLabel: "Commit to Role (RF)", sliderMaxLabel: "Negotiate Fluidity (I)", elementKeyMin: "RF", elementKeyMax: "I" },
    { id: "ED_P01", elementFocus: ["P", "RF"], situation: "Need for psychological surrender [P-Sub] vs. partner's dislike of helplessness [High RF].", question: "Negotiation focus?", sliderMinLabel: "Partner's Comfort (RF)", sliderMaxLabel: "Your Need (P)", elementKeyMin: "RF", elementKeyMax: "P" },
    { id: "ED_RF01", elementFocus: ["RF", "P"], situation: "Dominant identity [High RF] vs. partner's need to playfully challenge [P].", question: "Internal reaction?", sliderMinLabel: "Appreciate Need (P)", sliderMaxLabel: "Assert Authority (RF)", elementKeyMin: "P", elementKeyMax: "RF" },
    { id: "ED_RF02", elementFocus: ["RF", "S"], situation: "Submissive identity [Low RF] craving intense sensation [S] vs. partner's focus on psychological control.", question: "Advocate for?", sliderMinLabel: "Partner's Style (RF)", sliderMaxLabel: "Intense Sensations (S)", elementKeyMin: "RF", elementKeyMax: "S" },
    { id: "ED_C01", elementFocus: ["C", "S"], situation: "Complex fantasy scenario [C] requires ignoring a minor physical discomfort [S].", question: "Prioritize mind or body?", sliderMinLabel: "Address Sensory (S)", sliderMaxLabel: "Maintain Cognitive Focus (C)", elementKeyMin: "S", elementKeyMax: "C" },
    { id: "ED_R01", elementFocus: ["R", "A"], situation: "Maintaining multiple relationships [R] limits energy for a new strong attraction [A].", question: "Focus drifts towards?", sliderMinLabel: "Nurture Existing (R)", sliderMaxLabel: "Explore New Spark (A)", elementKeyMin: "R", elementKeyMax: "A" },
 ];

// --- Reflection Prompts ---
const reflectionPrompts = { /* ... FULL PROMPT LIST ... */
    "Attraction": [ { id: "pA1", text: "Recall someone (or something!) that recently sparked that 'whoa!' feeling. Pinpoint *exactly* what element(s) resonated so strongly?" }, { id: "pA2", text: "Think about a time your 'Desire Compass' pointed somewhere unexpected. What was that detour about? What insight did you glean?" }, { id: "pA3", text: "How does feeling emotionally close/safe impact your sexual attraction dial? Does trust turn up the volume, or are they separate frequencies?" }, { id: "pA4", text: "Ever had a powerful attraction fizzle out? What changed? Them, you, the situation, or the magic completing its cycle?" } ],
    "Interaction": [ { id: "pI1", text: "Picture your most satisfying intimate dance. Were you leading, following, or in fluid improv? What made it feel 'right'?" }, { id: "pI2", text: "Conjure your ideal encounter vibe... Playful? Intense? Tender? Authoritative? Yielding? Describe the essential energy." }, { id: "pI3", text: "Words or vibes? How much do you rely on explicit communication versus intuitively sensing energy shifts and unspoken cues?" }, { id: "pI4", text: "If exploring power dynamics... what's the juicy part about being in charge? What's the appeal or release in yielding?" } ],
    "Sensory": [ { id: "pS1", text: "Beyond orgasm, what pure *touch* feels amazing? Light? Firm? Rough? Specific fabrics or temperatures?" }, { id: "pS2", text: "Any highly specific sensations – heat, pressure, sting, sounds, smells – that reliably amplify arousal? Any instant 'no-gos'?" }, { id: "pS3", text: "Does your 'Feeling Finder' preference change significantly based on mood, stress, or partner? How flexible is your sensory map?" }, { id: "pS4", text: "Recall a purely sensory moment (intimate or not!) that felt incredibly satisfying or present. What ingredients made it potent?" } ],
    "Psychological": [ { id: "pP1", text: "Beyond physical pleasure, what deep-down core *need* does intimacy most often fulfill? Connection? Power? Validation? Escape? Comfort? Name the quest." }, { id: "pP2", text: "Remember an intimacy that felt *profoundly* satisfying on a soul level. What core need felt truly met or seen?" }, { id: "pP3", text: "Contrast with a time intimacy felt 'meh' psychologically, even if physically okay. What essential ingredient was missing?" }, { id: "pP4", text: "How does choosing to lower your guard, embrace vulnerability, and be truly 'seen' play into your most rewarding connections?" } ],
    "Cognitive": [ { id: "pC1", text: "How much happens in your mind's theater? Detailed fantasy? Analysis? Or grounded in the present moment's sensations/emotions?" }, { id: "pC2", text: "Dish on a specific fantasy, scenario, or mental play that reliably gets your brain buzzing. What's the secret ingredient?" }, { id: "pC3", text: "Does the mental game – banter, strategy, intellectual challenge – turn you on as much (or more than) the purely physical?" }, { id: "pC4", text: "How do *anticipation* (planned scenes) or *memory* (replaying moments) enhance or spice up your current experiences?" } ],
    "Relational": [ { id: "pR1", text: "In which context (solitude, dyad, casual, group) do you feel most free and authentic in expressing your full sexy self?" }, { id: "pR2", text: "Rules vs. Vibes vs. Anarchy: How important are clear agreements, exclusivity rules, or hierarchies? Or do you prefer organic evolution?" }, { id: "pR3", text: "What's your sweet spot for emotional closeness and vulnerability in sexual connections? Deep? Light? Does it vary?" }, { id: "pR4", text: "If non-monogamous (or considering): How do jealousy/insecurity show up? How do you experience/cultivate compersion (joy in partner's joy)?" } ],
    "RoleFocus": [ { id: "pRF1", text: "Consider feeling powerfully 'in charge' (sexual or not). What did that feel like physically/mentally? Where did confidence stem from?" }, { id: "pRF2", text: "Recall willingly, trustingly following another's lead. What was the emotional quality? Relief, vulnerability, excitement, peace?" }, { id: "pRF3", text: "If a Switch, what triggers the desire to shift polarity? Internal? External? What's enjoyable about the shift itself?" }, { id: "pRF4", text: "How does your Role Focus (D/s/W/Neutral) interact with other elements? High RF + High Control [I]? Low RF + seeking Comfort [P]?" } ],
    "Dissonance": [ { id: "pD1", text: "This Concept feels like static! Acknowledge discomfort, then lean in: What specific *part* makes you tilt your head and go 'Huh, unexpectedly interesting...'?" }, { id: "pD2", text: "Exploring unfamiliar map edges! Even if this feels challenging, what *potential* new insight or unexpected pleasure might hypothetically leaning into it offer?" }, { id: "pD3", text: "Sometimes things we push away mirror something within. Does this poke at a fear, taboo, or hidden desire/need you haven't acknowledged?" }, { id: "pD4", text: "How could simply *understanding* this different perspective broaden appreciation for your own complexity or the variety of human desire?" } ],
    "RareConcept": { "rP08": { id: "rP08", text: "Heavy Impact: Intense! Core allure?" }, "rP09": { id: "rP09", text: "Non-Impact Pain: Quality of 'ouch'?" }, "rP11": { id: "rP11", text: "Command & Control: Thrill?" }, "rP12": { id: "rP12", text: "Objectification Play: Need/fantasy?" }, "rP14": { id: "rP14", text: "Fantasy Immersion: Captivating ingredients?" }, "rP16": { id: "rP16", text: "Rope Bondage: Appeal?" }, "rP17": { id: "rP17", text: "Restriction/Helplessness: Emotions?" }, "rP20": { id: "rP20", text: "Material Focus: Dominant sense?" }, "rP21": { id: "rP21", text: "Uniform/Clothing Fetish: Spark?" }, "rP25": { id: "rP25", text: "Polyamory: Joys/challenges?" }, "rP27": { id: "rP27", text: "Relationship Anarchy: How build trust?" }, "rP30": { id: "rP30", text: "High Protocol D/s: Appeal?" }, "rP38": { id: "rP38", text: "Tease & Denial: Most potent part?" }, "rP41": { id: "rP41", text: "Erotic Hypnosis: Safety/ethics?" }, "rP42": { id: "rP42", text: "Transformation Fetish: Intrigue?" }, "rP43": { id: "rP43", text: "Medical Play: Core draw?" }, "rP44": { id: "rP44", text: "Edge Play: Safety non-negotiables?" }, "rP45": { id: "rP45", text: "Humiliation/Degradation: Your line?" }, "rP63": { id: "rP63", text: "Breath Play: Feeling sought? (Safety!)" }, "rP64": { id: "rP64", text: "CNC: Ensuring *real* consent?" }, "rP65": { id: "rP65", text: "Chemsex/PnP: Motivations/risks?" }, "rP109": { id: "rP109", text: "M/s Dynamic: Significance?" }, "rP111": { id: "rP111", text: "Knife Play: Thrill?" }, "rP112": { id: "rP112", text: "E-Stim: Intrigue?" }, "rP113": { id: "rP113", text: "Suspension Bondage: Appeal?" }, "rP114": { id: "rP114", text: "Water Sports: Buttons pushed?" }, "rP115": { id: "rP115", text: "Scat Play: Themes? (Safety!)" }, "rP116": { id: "rP116", text: "Blood Play: Symbolism? (Safety!)" }, "rP117": { id: "rP117", text: "Abduction Fantasy: Charged part?" }, "rP118": { id: "rP118", text: "Somnophilia: Ethical lines?" }, "rP119": { id: "rP119", text: "Orgasm Control: Communication?" }, "rP120": { id: "rP120", text: "Psychological 'Torture': Aftercare?" }, "rP121": { id: "rP121", text: "Furry Sexuality: Blend?" }, "rP122": { id: "rP122", text: "Autassassinophilia: Thrill? (Safety!)" }, "rP123": { id: "rP123", text: "Exposure Therapy Play: Safety/support?" }, "rP124": { id: "rP124", text: "Sensory Overstimulation: Goal?" }, "rP125": { id: "rP125", text: "Advanced Breath Control: Edge sought? (Safety!)" } },
    "General": [ { id: "pG1", text: "Reflecting on the last few encounters, which element felt most dominant in your approach?" }, { id: "pG2", text: "What card in your deck currently feels most 'you'? Why?" }, { id: "pG3", text: "What aspect of yourself are you currently neglecting or avoiding in this Labyrinth?" } ]
};

// --- Element Deep Dive Content ---
const elementDeepDive = { /* ... FULL DEEP DIVE CONTENT ... */
    "Attraction": [ { level: 1, title: "Level 1: Deciphering the Spark", insightCost: 10, content: "<p>Attraction: observe your *initial* magnetic pull..." }, { level: 2, title: "Level 2: Deeper Magnetic Fields", insightCost: 25, content: "<p>Is it Sapiosexuality [60]? Roles [I]? Fetish [20, 21]? Demisexuality [29]?" }, { level: 3, title: "Level 3: Spark to Flame", insightCost: 50, content: "<p>Spontaneous or responsive desire? How fixed is your compass? How is attraction sustained?" } ],
    "Interaction": [ { level: 1, title: "Level 1: The Dance of Connection", insightCost: 10, content: "<p>Interaction is the energetic exchange... Lead [4]? Follow [5]? Switch [6]?" }, { level: 2, title: "Level 2: Styles of Engagement", insightCost: 25, content: "<p>What's the *flavor*? Control [11]? Service [10]? Primal [40]? Nurturing [58]? Teasing [38]?" }, { level: 3, title: "Level 3: Language of Play", insightCost: 50, content: "<p>Communication style? Safewords? Aftercare [69]?" } ],
    "Sensory": [ { level: 1, title: "Level 1: Body's Alphabet", insightCost: 10, content: "<p>Skin speaks... Gentle [2]? Firm? Temperature? Textures?" }, { level: 2, title: "Level 2: Amplifying Sensation", insightCost: 25, content: "<p>Louder messages... Pinch/bite [9]? Impact [7, 8]? Wax [9]? Binding [16, 87]? Cold [88]? E-stim [112]? Pleasure/pain edge?" }, { level: 3, title: "Level 3: Symphony for Senses", insightCost: 50, content: "<p>Other senses? Scent [A]? Sound [32]? Visuals [21]? Sensory deprivation [37]?" } ],
    "Psychological": [ { level: 1, title: "Level 1: Heart's Compass", insightCost: 10, content: "<p>Deeper needs? Connection [15]? Power [4/5]? Validation [50]? Escape [51]? Comfort [80]? Primal [40]? Catharsis?" }, { level: 2, title: "Level 2: Emotional Landscapes", insightCost: 25, content: "<p>Comfort with vulnerability? Catharsis? Altered states ('subspace')? Safety net?" }, { level: 3, title: "Level 3: Inner Alchemy", insightCost: 50, content: "<p>Intimacy as mirror... healing [123]? Repeating patterns? Conscious self-discovery?" } ],
    "Cognitive": [ { level: 1, title: "Level 1: Theater of the Mind", insightCost: 10, content: "<p>How active is your inner world? Fantasy [14]? Analysis? Grounded [S]?" }, { level: 2, title: "Level 2: Scripts & Scenarios", insightCost: 25, content: "<p>Relish roles [13]? Scenarios (medical [43], capture [117])? Power dynamics [4/5]? Is the 'story' key?" }, { level: 3, title: "Level 3: Intellectual Spark", insightCost: 50, content: "<p>Mind as erogenous zone? Banter [74]? Analysis? Symbols, rules [30], rituals [101]? How thought fuels fire?" } ],
    "Relational": [ { level: 1, title: "Level 1: Mapping Connections", insightCost: 10, content: "<p>Structure? Monogamy [22]? Solo? CNM (Poly [25], Open [26])? Swinging [23]? Group [34]?" }, { level: 2, title: "Level 2: Defining Bonds", insightCost: 25, content: "<p>Depth/type? Deep intimacy [15]? Casual [24]? Commitment levels? Vary between partners?" }, { level: 3, title: "Level 3: Navigating the Cosmos", insightCost: 50, content: "<p>Multiple connections: Rules/hierarchy? RA [27]? Jealousy/compersion? Communication skills?" } ],
    "RoleFocus": [ { level: 1, title: "Level 1: Sensing the Current", insightCost: 10, content: "<p>Innate polarity in power dynamics... Dominant? Submissive? Switch?" }, { level: 2, title: "Level 2: Embodied Expressions", insightCost: 25, content: "<p>How polarity translates? Dom: Control [11], guidance? Sub: Obedience [5], service [10]? Switch: Scenarios?" }, { level: 3, title: "Level 3: Alchemy of Exchange", insightCost: 50, content: "<p>Interaction with partners [R]? Complementary energies? Communication [C]? Trust [15]?" } ]
};

// --- Elemental Insights ---
const elementalInsights = [ /* ... FULL INSIGHTS LIST ... */
    { id: "EI_A01", element: "A", text: "Attraction's compass needle doesn't always point north..." }, { id: "EI_A02", element: "A", text: "What makes you recoil... defines desire's edge." }, { id: "EI_A03", element: "A", text: "Strongest gravity pulls... towards the utterly unknown." }, { id: "EI_A04", element: "A", text: "A shared glance... subtle synchronicities..." }, { id: "EI_A05", element: "A", text: "Absence of attraction (Asexuality)... a different landscape." },
    { id: "EI_I01", element: "I", text: "Every touch, word, silence... a move in the dance." }, { id: "EI_I02", element: "I", text: "Perfect stillness... speaks volumes of trust or control." }, { id: "EI_I03", element: "I", text: "True power... most potent when willingly given." }, { id: "EI_I04", element: "I", text: "Compelling rhythm... in shared breath." }, { id: "EI_I05", element: "I", text: "Switching roles... mastery of the full spectrum." },
    { id: "EI_S01", element: "S", text: "Skin keeps an honest score..." }, { id: "EI_S02", element: "S", text: "Pain... intense sensation knocking... you decide how to answer." }, { id: "EI_S03", element: "S", text: "Muffle one sense... witness how others awaken." }, { id: "EI_S04", element: "S", text: "Awareness sharpens... on sensory contrast." }, { id: "EI_S05", element: "S", text: "Line between pleasure and pain... a shimmering veil." },
    { id: "EI_P01", element: "P", text: "Core psychological need... the invisible river carving desire." }, { id: "EI_P02", element: "P", text: "To be truly seen... a quiet, profound superpower." }, { id: "EI_P03", element: "P", text: "Catharsis through intensity... burn down old structures." }, { id: "EI_P04", element: "P", text: "Trust is the sacred cup... intimacy the wine." }, { id: "EI_P05", element: "P", text: "Binding the body... can free the mind." },
    { id: "EI_C01", element: "C", text: "The mind: ultimate playground, first frontier, final sanctuary." }, { id: "EI_C02", element: "C", text: "Every potent scene built twice: thought then flesh." }, { id: "EI_C03", element: "C", text: "Meaning adds spice... intellect hones interaction." }, { id: "EI_C04", element: "C", text: "Anticipation... savoring the wait..." }, { id: "EI_C05", element: "C", text: "Fantasy allows safe exploration." },
    { id: "EI_R01", element: "R", text: "Two hearts entwined... Many hearts connected..." }, { id: "EI_R02", element: "R", text: "Rules build fences; agreements build bridges." }, { id: "EI_R03", element: "R", text: "Exclusivity... a deliberate choice, not inherent rule." }, { id: "EI_R04", element: "R", text: "Compersion... joy in partner's joy." }, { id: "EI_R05", element: "R", text: "Relationship Anarchy... radical responsibility." },
    { id: "EI_RF01", element: "RF", text: "Dominance is responsibility; Submission is trust." }, { id: "EI_RF02", element: "RF", text: "True Switch finds power in the dance between poles." }, { id: "EI_RF03", element: "RF", text: "Clarity of role creates freedom; ambiguity requires negotiation." },
];

// --- Card Pools ---
const cardPools = { /* ... FULL POOLS LIST ... */
    "common_attacks": [1, 3, 100, 101, 102, 103, 67],
    "common_skills": [2, 31, 104, 105, 106, 107, 32, 74],
    "interaction_focus": [100, 101, 107, 112, 116, 4, 6, 11],
    "cognitive_draw_scry": [10003, 102, 104, 106, 119, 49, 13, 14, 118], // Added Mind Shatter
    "sensory_debuffs": [3, 7, 110, 9, 16], // Added Rope Bondage
    "psychological_defense": [10002, 2, 31, 105, 113, 5, 122, 15, 12, 17, 46], // Added more
    "rare_powers": [11, 14, 21, 114, 115, 121, 122, 123], // Removed uncommon powers 4,5,6,15
    "rolefocus_cards": [4, 5, 6, 10, 11, 12, 16, 17, 20, 21, 8, 9, 135], // Added heavy impact, pain, embrace pain
};

// --- Mirror Quiz Data ---
const quizQuestions = [ /* ... FULL QUIZ QUESTIONS ... */
    { id: "q_interaction", text: "When connecting intimately, your natural inclination is towards:", choices: [ { text: "Taking the lead, guiding the energy.", value: 'lead' }, { text: "Following the flow, adapting to your partner.", value: 'follow' }, { text: "A fluid exchange, shifting roles freely.", value: 'switch' } ] },
    { id: "q_sensory", text: "Which sensation offers the most profound release or connection?", choices: [ { text: "Gentle, comforting touch and warmth.", value: 'gentle' }, { text: "Intense pressure, sharp focus, or impact.", value: 'intense' }, { text: "The beauty of intricate patterns (visual/tactile).", value: 'pattern' } ] },
    { id: "q_psychological", text: "The deepest 'why' behind your desire often stems from:", choices: [ { text: "Seeking profound emotional connection and trust.", value: 'connection' }, { text: "Exploring power dynamics and testing limits.", value: 'power' }, { text: "Expressing creativity and escaping the mundane.", value: 'expression' } ] },
    { id: "q_cognitive", text: "During intimacy, your mind is most engaged by:", choices: [ { text: "Immersive fantasy worlds and specific scenarios.", value: 'fantasy' }, { text: "Witty banter, clever wordplay, or shared ideas.", value: 'banter' }, { text: "Analyzing the dynamic and psychological undercurrents.", value: 'analysis' } ] },
    { id: "q_relational", text: "You feel most authentic exploring intimacy within:", choices: [ { text: "A deeply committed, exclusive bond.", value: 'mono' }, { text: "Multiple connections, navigated ethically.", value: 'poly' }, { text: "Spontaneous encounters, free from defined structure.", value: 'casual' } ] }
];
const QUIZ_MAP = { /* ... FULL QUIZ MAP ... */
    q_interaction: { lead:   { cards: [4], att: ['I', 'RF'] }, follow: { cards: [5], att: ['P', 'RF'] }, switch: { cards: [6], att: ['C', 'I'] } },
    q_sensory: { gentle:  { cards: [2], att: ['S', 'P'] }, intense: { cards: [7], att: ['S', 'I'] }, pattern: { cards: [16], att: ['S', 'C'] } },
    q_psychological: { connection: { cards: [15], att: ['P', 'R'] }, power:      { cards: [11], att: ['P', 'I', 'RF'] }, expression: { cards: [13], att: ['P', 'C'] } },
    q_cognitive: { fantasy: { cards: [14], att: ['C', 'A'] }, banter:  { cards: [32], att: ['C', 'I'] }, analysis:{ cards: [60], att: ['C', 'P'] } },
    q_relational: { mono:   { cards: [31], att: ['R', 'P'] }, poly:   { cards: [25], att: ['R', 'C'] }, casual: { cards: [1], att: ['R', 'A'] } } // Using ID 25 for Poly
};


// --- FINAL EXPORT BLOCK ---
export {
    // Core Data Structures
    elementDetails,
    concepts,
    elementKeyToFullName,
    cardTypeKeys,
    elementNames,

    // Gameplay Data (Events, Info)
    elementalDilemmas,
    reflectionPrompts,
    elementDeepDive,
    elementalInsights,

    // Roguelite Specific Data
    milestones,
    quizQuestions, // Added previously
    QUIZ_MAP, // Added previously
    cardPools // NEW
};

console.log("data.js successfully loaded & EXPANDED. (v5.2 - COMPLETE & VERIFIED)");
// --- END OF FILE data.js ---
